#!/usr/bin/env node
/* Generate client/renderer/icons.js from Lucide's SVG source.
 *
 * The app had emoji and stray Unicode glyphs standing in for icons (🕐 📍 🏷,
 * ⌕ ⟳ ☾). They don't share a stroke weight, a grid, or an optical size —
 * some render in colour and some don't, because they're not icons, they're
 * text. It is the single loudest "nobody drew this" signal in the UI.
 *
 * We can't pull an icon font or a CDN: the renderer's CSP is
 * `default-src 'none'` and this project has no build step. So the paths get
 * baked into a source file, once, by this script. Re-run it to add an icon.
 *
 * Usage:  npm i --no-save lucide-static && node scripts/build-iconset.js
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'client', 'renderer', 'icons.js');

/* name in our code -> lucide file. Kept explicit so the mapping is reviewable:
 * "which glyph did we decide means 'repeat'" is a design decision, not a
 * lookup. */
const WANTED = {
  clock: 'clock',
  pin: 'map-pin',
  tag: 'tag',
  calendar: 'calendar',
  'calendar-days': 'calendar-days',
  users: 'users',
  repeat: 'repeat',
  pencil: 'pencil',
  cake: 'cake',
  bell: 'bell',
  'bell-off': 'bell-off',
  link: 'link',
  'list-checks': 'list-checks',
  list: 'list',
  menu: 'menu',
  columns: 'columns-3',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-down': 'chevron-down',
  search: 'search',
  refresh: 'refresh-cw',
  sun: 'sun',
  moon: 'moon',
  monitor: 'monitor',
  plus: 'plus',
  x: 'x',
  check: 'check',
  power: 'power',
  download: 'download',
  'arrow-right': 'arrow-right',
  home: 'house',
  'user-plus': 'user-plus',
  'arrow-left-right': 'arrow-left-right',
  square: 'square',
  'square-check': 'square-check-big',
  star: 'star',
  trash: 'trash-2',
  sliders: 'sliders-horizontal',
  'external-link': 'external-link',
  map: 'map-pin',
  info: 'info',
  keyboard: 'keyboard',
  palette: 'palette',
  send: 'send-horizontal',
  'message-circle': 'message-circle',
};

const dir = path.join(ROOT, 'node_modules', 'lucide-static', 'icons');
const alt = path.join(process.env.TEMP || '', 'x');
if (!fs.existsSync(dir)) {
  console.error('lucide-static is not installed.\n  npm i --no-save lucide-static');
  process.exit(1);
}

const version = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'node_modules', 'lucide-static', 'package.json'), 'utf8')
).version;

const body = {};
for (const [name, file] of Object.entries(WANTED)) {
  const p = path.join(dir, file + '.svg');
  if (!fs.existsSync(p)) { console.error('missing lucide icon:', file); process.exit(1); }
  const svg = fs.readFileSync(p, 'utf8');
  // Keep only what's inside <svg>…</svg>, and flatten it: the wrapper's
  // attributes are applied by icon() so every icon shares one stroke and grid.
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
  body[name] = inner.replace(/\s*\n\s*/g, '').trim();
}

const out = `/* Icons. GENERATED by scripts/build-iconset.js — do not edit by hand.
 *
 * Paths from Lucide v${version} (ISC). https://lucide.dev
 * Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
 * part of Feather (MIT). All other copyright (c) for Lucide are held by
 * Lucide Contributors 2022.
 *
 * Baked in rather than fetched: the renderer's CSP is default-src 'none' and
 * this project has no build step. One stroke weight, one 24px grid, one
 * optical size — which is the entire point of using a real set instead of
 * whatever glyph the font happened to have.
 */
(() => {
  const TTX = (globalThis.TTX = globalThis.TTX || {});
  const NS = 'http://www.w3.org/2000/svg';

  const PATHS = ${JSON.stringify(body, null, 4).replace(/\n/g, '\n  ')};

  /**
   * An icon element. \`stroke\` is currentColor, so an icon takes the colour of
   * the text it sits with — the thing emoji could never do.
   *
   * Lucide draws on a 24px grid with a 2px stroke. Scaling that to 16px would
   * thin the stroke to 1.33px and land it off the pixel grid, which is how you
   * get the greyish, slightly-blurry look. Scale the stroke back up so the
   * rendered weight stays ~1.5px at any size.
   */
  function icon(name, size = 16) {
    const el = document.createElementNS(NS, 'svg');
    const d = PATHS[name];
    if (!d) return el;
    el.setAttribute('viewBox', '0 0 24 24');
    el.setAttribute('width', size);
    el.setAttribute('height', size);
    el.setAttribute('fill', 'none');
    el.setAttribute('stroke', 'currentColor');
    el.setAttribute('stroke-width', (1.5 * 24 / size).toFixed(2));
    el.setAttribute('stroke-linecap', 'round');
    el.setAttribute('stroke-linejoin', 'round');
    // Decorative by default: these sit beside a text label almost everywhere,
    // and a screen reader announcing "clock, 日時" is worse than silence.
    // Icon-only buttons carry their own aria-label.
    el.setAttribute('aria-hidden', 'true');
    el.setAttribute('focusable', 'false');
    el.classList.add('i');
    el.innerHTML = d;
    return el;
  }

  TTX.icon = icon;
  TTX.iconNames = Object.keys(PATHS);
})();
`;

fs.writeFileSync(OUT, out);
console.log(`wrote ${path.relative(ROOT, OUT).replace(/\\/g, '/')} — ${Object.keys(body).length} icons from lucide ${version}`);
