#!/usr/bin/env node
/* Rasterise the docs/*.svg into the docs/*.png the README actually shows.
 *
 * GitHub proxies README <img> through camo, which renders an SVG as a
 * broken-image icon often enough — and reliably on a private repo — that the
 * banner and badges simply didn't appear. PNGs are dependable. The SVGs stay
 * the source of truth (generated by tools/badges.js, the banners hand-drawn);
 * this is the one downstream step that turns them into what renders.
 *
 *   npm run inspect            # a running client with a debugging port
 *   node tools/rasterise-docs.js
 *
 * It borrows the running client's Chromium over CDP rather than pulling in a
 * browser dependency — the same reason the verify-*.js scripts do, and why
 * playwright-core is a --no-save dev-only install. CI can't run this (no
 * display), so scripts/check.js instead verifies the PNGs it produces exist.
 */
const fs = require('node:fs');
const path = require('node:path');

const DOCS = path.join(__dirname, '..', 'docs');
const CDP = process.env.TTX_CDP || 'http://127.0.0.1:9333';

// The banner is the only SVG the README shows as a PNG — it's a big hand-drawn
// image where a rasterised copy is more dependable across viewers. The badges
// are referenced as SVG directly (they render at their true size that way), so
// they aren't rasterised.
const TARGETS = [
  { svg: 'banner-light.svg', w: 1160, h: 290 },
  { svg: 'banner-dark.svg', w: 1160, h: 290 },
];

(async () => {
  let chromium;
  try { ({ chromium } = require('playwright-core')); } catch {
    console.error('playwright-core is not installed — run:\n'
      + '  npm i --no-save --no-package-lock playwright-core');
    process.exit(2);
  }
  const b = await chromium.connectOverCDP(CDP).catch(() => null);
  if (!b) {
    console.error(`no client on ${CDP} — start one with \`npm run inspect\` first`);
    process.exit(2);
  }
  const page = b.contexts()[0].pages().find((p) => p.url().includes('index.html'));
  if (!page) { console.error('client is up but no renderer page found'); await b.close(); process.exit(2); }

  for (const t of TARGETS) {
    let svg = fs.readFileSync(path.join(DOCS, t.svg), 'utf8');
    const w = t.w || Number(svg.match(/width="(\d+)"/)?.[1]);
    const h = t.h || 20;
    if (t.w) svg = svg.replace('<svg ', `<svg width="${w}" height="${h}" `);
    // A shadow root so the app's own CSS cannot reach in, transparent so the
    // badge corners stay rounded against any README background.
    await page.evaluate(({ svg: s, w: ww, h: hh }) => {
      document.getElementById('ras')?.remove();
      const d = document.createElement('div');
      d.id = 'ras';
      d.style.cssText = 'position:fixed;inset:0;z-index:99999;background:transparent';
      const host = document.createElement('div');
      host.style.cssText = `position:absolute;top:0;left:0;width:${ww}px;height:${hh}px`;
      host.attachShadow({ mode: 'open' }).innerHTML = s;
      d.appendChild(host);
      document.body.appendChild(d);
    }, { svg, w, h });
    await page.waitForTimeout(250);
    const png = t.svg.replace(/\.svg$/, '.png');
    await (await page.$('#ras > div')).screenshot({
      path: path.join(DOCS, png), scale: 'device', omitBackground: true,
    });
    console.log(`docs/${png}  (${w}×${h})`);
  }

  await page.evaluate(() => document.getElementById('ras')?.remove());
  await b.close();
})().catch((e) => { console.error(e.message); process.exit(1); });
